#!/bin/bash
#Script to autoexecute several experiments with varying parameters
clear
python exps.py fashion vgg1 all 100 5 100 no results/uncertainty/exp9
python exps.py cifar vgg1 all 100 5 100 no results/uncertainty/exp10
python exps.py imnet vgg1 all 100 5 100 no results/uncertainty/exp11
python exps.py vgg2f vgg1 all 100 5 100 no results/uncertainty/exp12

python exps.py fashion vgg2 all 100 5 100 no results/uncertainty/exp13
python exps.py cifar vgg2 all 100 5 100 no results/uncertainty/exp14
python exps.py imnet vgg2 all 100 5 100 no results/uncertainty/exp15
python exps.py vgg2f vgg2 all 100 5 100 no results/uncertainty/exp16

python look_at_this_graph.py uncertainty/exp
