#!/bin/bash
#Script to autoexecute several experiments with varying parameters
#First parameter should be the directory of datasets
clear

fashion="$1/fashion/fashion.hdf5"
cifar="$1/cifar/cifar.hdf5"
imnet="$1/immnet/imnet.hdf5"
vgg2f="$1/vgg2f/vgg2f.hdf5"

python exps.py $fashion vgg1 all 100 1 2 100 no results/uncertainty/exp1
python exps.py $cifar vgg1 all 100 1 2 100 no results/uncertainty/exp2
python exps.py $imnet vgg1 all 100 1 2 100 no results/uncertainty/exp3
python exps.py $vgg2f vgg1 all 100 1 2 100 no results/uncertainty/exp4

python exps.py $fashion vgg2 all 100 1 2 100 no results/uncertainty/exp5
python exps.py $cifar vgg2 all 100 1 2 100 no results/uncertainty/exp6
python exps.py $imnet vgg2 all 100 1 2 100 no results/uncertainty/exp7
python exps.py $vgg2f vgg2 all 100 1 2 100 no results/uncertainty/exp8
