#!/bin/bash
#Script to autoexecute several experiments with varying parameters
clear
python exps.py fashion vgg1 all 100 2 100 yes results/pseudo/exp1
python exps.py cifar vgg1 all 100 2 100 yes results/pseudo/exp2
python exps.py imnet vgg1 all 100 2 100 yes results/pseudo/exp3
python exps.py vgg2f vgg1 all 100 2 100 yes results/pseudo/exp4

python exps.py fashion vgg2 all 100 2 100 yes results/pseudo/exp5
python exps.py cifar vgg2 all 100 2 100 yes results/pseudo/exp6
python exps.py imnet vgg2 all 100 2 100 yes results/pseudo/exp7
python exps.py vgg2f vgg2 all 100 2 100 yes results/pseudo/exp8

python look_at_this_graph.py pseudo/exp
